# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-latest]
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    
    env:
      FC: gfortran
      OMPI_FC: gfortran
      LIBACCESSOM2_ROOT: ${{ github.workspace }}/libaccessom2
      platform: ubuntu

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code 
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Determing OS version
        uses: kenchan0130/actions-system-info@master
        id: system-info

      - name: Set OS version
        run: | 
          echo "Release: ${{ steps.system-info.outputs.release }}"
          echo "os_version=${{ steps.system-info.outputs.release }}" >> $GITHUB_ENV
      
      - name: Fake build
        run: |
          echo $(date) ${{ env.os_version}} ${{ github.ref }} > build.txt
      
      - name: Debug
        run: |
          echo "Ref: ${{ github.ref }}"

      - name: Prepare release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          tar -cvf binary_release_${{ env.os_version}}.tar build.txt

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "binary_release-*.tar.gz"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
